name: Test_cpp_gh_action
on:
  schedule:
    - cron : '15 19 * * *' # Every day at 19h15

  
jobs:
  build-linux:
    name: Compile_under_inux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: nxxm_CI 
        uses: nxxm/cpp-gh-action.@master
        with: 
          target: "gcc-7-cxx17"
          config: "Release"
          extra_args: "--verbose"
          jobs: "4"
      - name: Upload the build directory
        uses: actions/upload-artifact@v2
        with:
          name: my_build
          path: ./build/
    env:
        NXXM_AUTH: ${{ secrets.NXXM_AUTH }}
          

  build-wasm:
    name: Compile_under_wasm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: nxxm_CI 
        uses: nxxm/cpp-gh-action.@master
      - name: Upload the build directory
        uses: actions/upload-artifact@v2
        with:
          name: my_build
          path: ./build/
    env:
        NXXM_AUTH: ${{ secrets.NXXM_AUTH }}

