name: CI
on:
  push:
    branches:
      - main
  pull_request:
env:
  NXXM_AUTH: ${{ secrets.NXXM_AUTH }}
  
jobs:
  build:
    name: Compile_under_linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: nxxm_CI 
        uses: nxxm/cpp-gh-action.@feature_use_official_docker
        with: 
          target: "gcc-7-cxx17"
          config: "Release"
          extra_args: "--force-upgrade"
          jobs: "4"
      - name: Upload the build directory
        uses: actions/upload-artifact@v2
        with:
          name: my_build
          path: ./build/



